//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public string Id { get; set; }
        public string Account { get; set; }
        public string PassWord { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateId { get; set; }
        public string RowStates { get; set; }
        public string IsLogin { get; set; }
    }
}
